<?php

namespace PublicBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
  public function getLastFiveArticles() {
    return $this
      ->createQueryBuilder('a')
      ->setMaxResults(5)
      ->orderBy('a.date', 'DESC')
      ->getQuery()
      ->getResult();
  }
}
