<?php

namespace PublicBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
  public function getLastFiveArticles() {
    return $this
      ->createQueryBuilder('a')
      ->setMaxResults(5)
      ->orderBy('a.date', 'DESC')
      ->getQuery()
      ->getResult();
  }

  public function getArticlesByTag($tag) {
    $request = $this->createQueryBuilder('a')
      ->leftJoin('a.tags', 't')
      ->where('t.id IN (:tags_id)')
      ->setParameter('tags_id', $tag)
      ->getQuery()
      ->getResult()
      ;
      return $request;
  }

  public function getArticlesByCategory($category) {
    $request = $this->createQueryBuilder('a')
      ->leftJoin('a.category', 'c')
      ->where('c.id IN (:category_id)')
      ->setParameter('category_id', $category)
      ->getQuery()
      ->getResult()
      ;
      return $request;
  }

}
