<?php

namespace PublicBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function getArticlesByTagName($searchedTagName) {
        $tag = $this->findByName($searchedTagName);
        var_dump($tag);
        $articles = $tag->getArticles();
        var_dump($articles);
        die();
    }
}
