# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        PublicBundle\Entity\User: plaintext
        #     algorithm: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        # in_memory:
        #     memory:
        #         users:
        #             user:
        #                 password: userpass
        #                 roles: 'ROLE_USER'
        bdd_provider:
            entity:
                class: PublicBundle:User
                property: name


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            #provider: in_memory
            form_login:
                login_path: login
                check_path: login
                default_target_path: administration
                provider: bdd_provider
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        #ROLE_USER required to access admin panel
        - { path: ^/administration, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/article, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/tag, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/category, roles: IS_AUTHENTICATED_REMEMBERED }

